[package]
name = "rust-palmtree"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
log = "0.4"
failure = "0.1"
lazy_static = "1.0"
itertools = "0.7"
time = "0.1"

[dev-dependencies]
pretty_env_logger = "0.2"
